import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "jan-samadhan-language";
const DEFAULT_LANGUAGE = "en";

export const languages = [
  { label: "English", code: "en" },
  { label: "Hindi", code: "hi" },
  { label: "Assamese", code: "as" },
  { label: "Bengali", code: "bn" },
  { label: "Bodo", code: "brx" },
  { label: "Dogri", code: "doi" },
  { label: "Gujarati", code: "gu" },
  { label: "Kannada", code: "kn" },
  { label: "Kashmiri", code: "ks" },
  { label: "Konkani", code: "kok" },
  { label: "Maithili", code: "mai" },
  { label: "Malayalam", code: "ml" },
  { label: "Manipuri", code: "mni" },
  { label: "Marathi", code: "mr" },
  { label: "Nepali", code: "ne" },
  { label: "Odia", code: "or" },
  { label: "Punjabi", code: "pa" },
  { label: "Sanskrit", code: "sa" },
  { label: "Santali", code: "sat" },
  { label: "Sindhi", code: "sd" },
  { label: "Tamil", code: "ta" },
  { label: "Telugu", code: "te" },
  { label: "Urdu", code: "ur" },
];

const translationKeys = {
  subtitle: "Citizen Grievance Intelligence Platform",
  home: "Home",
  contactUs: "Contact Us",
  aboutUs: "About Us",
  siteMap: "Site Map",
  track: "Track",
  signIn: "Sign In",
  eyebrow: "Modern Jan Samadhan AI grievance platform",
  headline: "Smart grievance redress for citizens.",
  intro: "Lodge complaints, classify them with AI, route them to the right authority, monitor SLA progress, and close the loop with feedback.",
  add: "Add Grievance",
  status: "View Status",
  process: "Redress Process",
  ai: "AI Classification",
  officers: "Nodal / Officers",
  assigned: "Complaint assigned",
  resolved: "Complaint resolved",
  assignedPlural: "complaints assigned",
  rate: "resolution rate",
  preview: "Live Routing Preview",
  workflow: "Assignment workflow",
  step1: "Citizen complaint submitted",
  step2: "Central / State grievance portal",
  step3: "Main Officer manages departments",
  step4: "Department head assigns officer",
  step5: "Sub officer coordinates field work",
  step6: "Citizen receives resolution update",
  departments: "Departments",
  levels: "Officer levels",
  sla: "SLA view",
  all: "All",
  rolePortal: "Role-Based Portal",
  workspaces: "Citizen, admin, and officer workspaces",
  citizen: "Citizen",
  admin: "Admin / Main Officer",
  officer: "Officer",
  citizenText: "Submit complaints, track ticket status, receive notifications, and give feedback after resolution.",
  adminText: "Add, edit, or disable departments, manage state and central offices, assign heads, and monitor all complaints.",
  officerText: "Review department complaints, assign sub officers, update status, upload proof, and close ground-level reports.",
  aiLayer: "AI Layer",
  aiTitle: "Classification engine built into the portal",
  multilingual: "Multilingual",
  routing: "Smart routing",
  verified: "Officer verified",
  aiEngine: "AI/ML Classification Engine",
  pretrained: "Pretrained Language Models",
  training: "Continuous Training",
  aiEngineText: "Supervised models classify complaints into departments with confidence scores.",
  pretrainedText: "BERT or similar transformer models can be plugged in for better text understanding.",
  trainingText: "Officer corrections and citizen feedback improve the model over time.",
  about: "About Jan Samadhan AI",
  aboutText: "A modern grievance platform inspired by public redress workflows. Citizens get a simple interface, officers get routed cases, and admins get visibility into categories, priorities, and SLA performance.",
  contact: "Contact",
  help: "FAQs/Help",
  contactText: "Reach support and department teams from the portal.",
  helpText: "Guide citizens through login, grievance filing, and tracking.",
  sitemapText: "Quick access to home, status, grievance, appeal, and dashboard flows.",
  footer: "Jan Samadhan AI | AI-powered Citizen Grievance Portal",
};

function pack(values) {
  return Object.fromEntries(
    Object.entries(values).map(([key, value]) => [translationKeys[key], value])
  );
}

const translations = {
  en: {},
  hi: pack({
    subtitle: "नागरिक शिकायत इंटेलिजेंस प्लेटफॉर्म", home: "होम", contactUs: "संपर्क करें", aboutUs: "हमारे बारे में", siteMap: "साइट मैप", track: "ट्रैक करें", signIn: "साइन इन",
    eyebrow: "आधुनिक जन समाधान AI शिकायत प्लेटफॉर्म", headline: "नागरिकों, अधिकारियों और प्रशासकों के लिए स्मार्ट शिकायत निवारण।", intro: "शिकायत दर्ज करें, AI से वर्गीकृत करें, सही अधिकारी तक भेजें, SLA प्रगति देखें और फीडबैक से प्रक्रिया पूरी करें।",
    add: "शिकायत जोड़ें", status: "स्थिति देखें", process: "निवारण प्रक्रिया", ai: "AI वर्गीकरण", officers: "नोडल / अधिकारी", assigned: "शिकायत सौंपी गई", resolved: "शिकायत हल हुई", assignedPlural: "शिकायतें सौंपी गईं", rate: "निवारण दर",
    preview: "लाइव रूटिंग पूर्वावलोकन", workflow: "असाइनमेंट कार्यप्रवाह", step1: "नागरिक ने शिकायत जमा की", step2: "केंद्रीय / राज्य शिकायत पोर्टल", step3: "मुख्य अधिकारी विभागों का प्रबंधन करता है", step4: "विभाग प्रमुख अधिकारी नियुक्त करता है", step5: "उप अधिकारी फील्ड कार्य का समन्वय करता है", step6: "नागरिक को समाधान अपडेट मिलता है",
    departments: "विभाग", levels: "अधिकारी स्तर", sla: "SLA दृश्य", all: "सभी", rolePortal: "भूमिका आधारित पोर्टल", workspaces: "नागरिक, प्रशासक और अधिकारी कार्यक्षेत्र", citizen: "नागरिक", admin: "प्रशासक / मुख्य अधिकारी", officer: "अधिकारी",
    citizenText: "शिकायत दर्ज करें, टिकट स्थिति देखें, सूचनाएं पाएं और समाधान के बाद फीडबैक दें।", adminText: "विभाग जोड़ें, संपादित करें या निष्क्रिय करें, प्रमुख नियुक्त करें और सभी शिकायतें देखें।", officerText: "विभागीय शिकायतें देखें, उप अधिकारी नियुक्त करें, स्थिति अपडेट करें, प्रमाण अपलोड करें और रिपोर्ट बंद करें।",
    aiLayer: "AI परत", aiTitle: "पोर्टल में बना वर्गीकरण इंजन", multilingual: "बहुभाषी", routing: "स्मार्ट रूटिंग", verified: "अधिकारी सत्यापित", aiEngine: "AI/ML वर्गीकरण इंजन", pretrained: "पूर्व प्रशिक्षित भाषा मॉडल", training: "निरंतर प्रशिक्षण", aiEngineText: "मॉडल शिकायतों को विश्वास स्कोर के साथ विभागों में वर्गीकृत करते हैं।", pretrainedText: "बेहतर पाठ समझ के लिए BERT जैसे मॉडल जोड़े जा सकते हैं।", trainingText: "अधिकारी सुधार और नागरिक फीडबैक मॉडल को बेहतर बनाते हैं।",
    about: "जन समाधान AI के बारे में", aboutText: "लोक शिकायत निवारण से प्रेरित आधुनिक शिकायत प्लेटफॉर्म।", contact: "संपर्क", help: "प्रश्न / सहायता", contactText: "पोर्टल से सहायता और विभागीय टीमों तक पहुंचें।", helpText: "लॉगिन, शिकायत दर्ज करने और ट्रैकिंग में मार्गदर्शन।", sitemapText: "होम, स्थिति, शिकायत, अपील और डैशबोर्ड तक त्वरित पहुंच।", footer: "जन समाधान AI | AI-संचालित नागरिक शिकायत पोर्टल",
  }),
  as: pack({
    subtitle: "নাগৰিক অভিযোগ বুদ্ধিমত্তা প্লেটফৰ্ম", home: "মুখ্য পৃষ্ঠা", contactUs: "যোগাযোগ কৰক", aboutUs: "আমাৰ বিষয়ে", siteMap: "ছাইট মেপ", track: "ট্ৰেক কৰক", signIn: "চাইন ইন",
    eyebrow: "আধুনিক জন সমাধান AI অভিযোগ প্লেটফৰ্ম", headline: "নাগৰিক, বিষয়া আৰু প্ৰশাসকৰ বাবে স্মাৰ্ট অভিযোগ নিষ্পত্তি।", intro: "অভিযোগ দাখিল কৰক, AI ৰে শ্ৰেণীবিভাজন কৰক, সঠিক কৰ্তৃপক্ষলৈ পঠাওক আৰু অগ্ৰগতি নিৰীক্ষণ কৰক।",
    add: "অভিযোগ যোগ কৰক", status: "স্থিতি চাওক", process: "নিষ্পত্তি প্ৰক্ৰিয়া", ai: "AI শ্ৰেণীবিভাজন", officers: "নোডাল / বিষয়া", assigned: "অভিযোগ আবণ্টিত", resolved: "অভিযোগ নিষ্পত্তি", assignedPlural: "অভিযোগ আবণ্টিত", rate: "নিষ্পত্তিৰ হাৰ",
    preview: "লাইভ ৰাউটিং পূৰ্বদৰ্শন", workflow: "আবণ্টন কৰ্মপ্ৰবাহ", step1: "নাগৰিকে অভিযোগ দাখিল কৰিলে", step2: "কেন্দ্ৰীয় / ৰাজ্য অভিযোগ পোৰ্টেল", step3: "মুখ্য বিষয়াই বিভাগ চলায়", step4: "বিভাগ মুৰব্বীয়ে বিষয়া নিযুক্ত কৰে", step5: "উপ বিষয়াই ক্ষেত্ৰ কাম সমন্বয় কৰে", step6: "নাগৰিকে সমাধান আপডেট পায়",
    departments: "বিভাগ", levels: "বিষয়া স্তৰ", sla: "SLA দৃশ্য", all: "সকলো", rolePortal: "ভূমিকা-ভিত্তিক পোৰ্টেল", workspaces: "নাগৰিক, প্ৰশাসক আৰু বিষয়া কৰ্মক্ষেত্ৰ", citizen: "নাগৰিক", admin: "প্ৰশাসক / মুখ্য বিষয়া", officer: "বিষয়া",
    aiLayer: "AI স্তৰ", aiTitle: "পোৰ্টেলত সংযুক্ত শ্ৰেণীবিভাজন ইঞ্জিন", multilingual: "বহুভাষিক", routing: "স্মাৰ্ট ৰাউটিং", verified: "বিষয়া যাচাইকৃত", about: "জন সমাধান AI বিষয়ে", contact: "যোগাযোগ", help: "প্ৰশ্ন / সহায়", footer: "জন সমাধান AI | AI-চালিত নাগৰিক অভিযোগ পোৰ্টেল",
  }),
  bn: pack({
    subtitle: "নাগরিক অভিযোগ বুদ্ধিমত্তা প্ল্যাটফর্ম", home: "হোম", contactUs: "যোগাযোগ করুন", aboutUs: "আমাদের সম্পর্কে", siteMap: "সাইট ম্যাপ", track: "ট্র্যাক করুন", signIn: "সাইন ইন",
    eyebrow: "আধুনিক জন সমাধান AI অভিযোগ প্ল্যাটফর্ম", headline: "নাগরিক, কর্মকর্তা এবং প্রশাসকদের জন্য স্মার্ট অভিযোগ নিষ্পত্তি।", intro: "অভিযোগ জমা দিন, AI দিয়ে শ্রেণীবিভাগ করুন, সঠিক কর্তৃপক্ষের কাছে পাঠান এবং অগ্রগতি দেখুন।",
    add: "অভিযোগ যোগ করুন", status: "স্থিতি দেখুন", process: "নিষ্পত্তি প্রক্রিয়া", ai: "AI শ্রেণীবিভাগ", officers: "নোডাল / কর্মকর্তা", assigned: "অভিযোগ বরাদ্দ", resolved: "অভিযোগ নিষ্পত্তি", assignedPlural: "অভিযোগ বরাদ্দ", rate: "নিষ্পত্তির হার",
    preview: "লাইভ রাউটিং প্রিভিউ", workflow: "বরাদ্দ কর্মপ্রবাহ", step1: "নাগরিক অভিযোগ জমা দিয়েছেন", step2: "কেন্দ্রীয় / রাজ্য অভিযোগ পোর্টাল", step3: "প্রধান কর্মকর্তা বিভাগ পরিচালনা করেন", step4: "বিভাগীয় প্রধান কর্মকর্তা নিয়োগ করেন", step5: "উপ কর্মকর্তা মাঠের কাজ সমন্বয় করেন", step6: "নাগরিক সমাধান আপডেট পান",
    departments: "বিভাগ", levels: "কর্মকর্তা স্তর", sla: "SLA দৃশ্য", all: "সব", rolePortal: "ভূমিকা-ভিত্তিক পোর্টাল", workspaces: "নাগরিক, প্রশাসক ও কর্মকর্তার কর্মক্ষেত্র", citizen: "নাগরিক", admin: "প্রশাসক / প্রধান কর্মকর্তা", officer: "কর্মকর্তা",
    aiLayer: "AI স্তর", aiTitle: "পোর্টালে নির্মিত শ্রেণীবিভাগ ইঞ্জিন", multilingual: "বহুভাষিক", routing: "স্মার্ট রাউটিং", verified: "কর্মকর্তা যাচাইকৃত", about: "জন সমাধান AI সম্পর্কে", contact: "যোগাযোগ", help: "প্রশ্ন / সাহায্য", footer: "জন সমাধান AI | AI-চালিত নাগরিক অভিযোগ পোর্টাল",
  }),
  brx: pack({ subtitle: "नागरिक शिकायत बुद्धिमत्ता प्लेटफर्म", home: "नुखा", contactUs: "सम्पर्क", aboutUs: "जोंनि सोमोन्दै", siteMap: "साइट मेप", track: "ट्रेक", signIn: "साइन इन", eyebrow: "आधुनिक जन समाधान AI शिकायत प्लेटफर्म", headline: "नागरिक, अफिसार आरो प्रशासकफोरनि थाखाय स्मार्ट शिकायत समाधान।", intro: "शिकायत जमा खालाम, AI जों बाखनाय, गेबें अफिसाराव दैथाय हर।", add: "शिकायत दाजाब", status: "थासारि नाय", process: "समाधान प्रक्रिया", ai: "AI बाखनाय", officers: "नोडाल / अफिसार", assigned: "शिकायत आबंटित", resolved: "शिकायत समाधान", assignedPlural: "शिकायत आबंटित", rate: "समाधान हार", preview: "लाइभ राउटिंग नायगिरनाय", workflow: "आबंटन कार्यप्रवाह", departments: "विभाग", levels: "अफिसार स्तर", sla: "SLA नायनाय", all: "गासै", rolePortal: "भूमिका-आधारित पोर्टेल", workspaces: "नागरिक, एडमिन आरो अफिसार कार्यक्षेत्र", citizen: "नागरिक", admin: "एडमिन / मुख्य अफिसार", officer: "अफिसार", aiLayer: "AI स्तर", aiTitle: "पोर्टेलनि वर्गीकरण इन्जिन", multilingual: "बहुभाषिक", routing: "स्मार्ट राउटिंग", verified: "अफिसार सत्यापित", contact: "सम्पर्क", help: "सहायता", footer: "जन समाधान AI | AI नागरिक शिकायत पोर्टेल" }),
  doi: pack({ subtitle: "नागरिक शिकायत इंटेलिजेंस प्लेटफॉर्म", home: "घर", contactUs: "संपर्क करो", aboutUs: "साड़े बारे", siteMap: "साइट मैप", track: "ट्रैक करो", signIn: "साइन इन", eyebrow: "आधुनिक जन समाधान AI शिकायत प्लेटफॉर्म", headline: "नागरिकें, अफसरें ते प्रशासकें लेई स्मार्ट शिकायत निवारण।", intro: "शिकायत दर्ज करो, AI कन्नै वर्गीकृत करो ते ठीक अधिकारी कोल भेजो।", add: "शिकायत जोड़ो", status: "स्थिति दिक्खो", process: "निवारण प्रक्रिया", ai: "AI वर्गीकरण", officers: "नोडल / अफसर", assigned: "शिकायत सौंपी गेई", resolved: "शिकायत हल होई", assignedPlural: "शिकायतां सौंपी गेइयां", rate: "निवारण दर", preview: "लाइव रूटिंग पूर्वदर्शन", workflow: "असाइनमेंट कार्यप्रवाह", departments: "विभाग", levels: "अफसर स्तर", sla: "SLA दृश्य", all: "सारे", rolePortal: "भूमिका आधारित पोर्टल", workspaces: "नागरिक, एडमिन ते अफसर कार्यक्षेत्र", citizen: "नागरिक", admin: "एडमिन / मुख्य अफसर", officer: "अफसर", aiLayer: "AI परत", aiTitle: "पोर्टल च बना वर्गीकरण इंजन", multilingual: "बहुभाषी", routing: "स्मार्ट रूटिंग", verified: "अफसर सत्यापित", contact: "संपर्क", help: "मदद", footer: "जन समाधान AI | AI नागरिक शिकायत पोर्टल" }),
  gu: pack({ subtitle: "નાગરિક ફરિયાદ ઇન્ટેલિજન્સ પ્લેટફોર્મ", home: "હોમ", contactUs: "સંપર્ક કરો", aboutUs: "અમારા વિશે", siteMap: "સાઇટ મેપ", track: "ટ્રેક કરો", signIn: "સાઇન ઇન", eyebrow: "આધુનિક જન સમાધાન AI ફરિયાદ પ્લેટફોર્મ", headline: "નાગરિકો, અધિકારીઓ અને વહીવટકર્તાઓ માટે સ્માર્ટ ફરિયાદ નિવારણ.", intro: "ફરિયાદ નોંધાવો, AI વડે વર્ગીકૃત કરો, યોગ્ય સત્તાધિકારી સુધી મોકલો અને પ્રગતિ જુઓ.", add: "ફરિયાદ ઉમેરો", status: "સ્થિતિ જુઓ", process: "નિવારણ પ્રક્રિયા", ai: "AI વર્ગીકરણ", officers: "નોડલ / અધિકારીઓ", assigned: "ફરિયાદ સોંપાઈ", resolved: "ફરિયાદ ઉકેલાઈ", assignedPlural: "ફરિયાદો સોંપાઈ", rate: "ઉકેલ દર", preview: "લાઇવ રૂટિંગ પૂર્વાવલોકન", workflow: "સોંપણી કાર્યપ્રવાહ", departments: "વિભાગો", levels: "અધિકારી સ્તરો", sla: "SLA દૃશ્ય", all: "બધા", rolePortal: "ભૂમિકા આધારિત પોર્ટલ", workspaces: "નાગરિક, એડમિન અને અધિકારી કાર્યસ્થળ", citizen: "નાગરિક", admin: "એડમિન / મુખ્ય અધિકારી", officer: "અધિકારી", aiLayer: "AI સ્તર", aiTitle: "પોર્ટલમાં બનેલું વર્ગીકરણ એન્જિન", multilingual: "બહુભાષી", routing: "સ્માર્ટ રૂટિંગ", verified: "અધિકારી ચકાસાયેલ", about: "જન સમાધાન AI વિશે", contact: "સંપર્ક", help: "પ્રશ્નો / મદદ", footer: "જન સમાધાન AI | AI નાગરિક ફરિયાદ પોર્ટલ" }),
  kn: pack({ subtitle: "ನಾಗರಿಕ ಅಹವಾಲು ಬುದ್ಧಿಮತ್ತೆ ವೇದಿಕೆ", home: "ಮುಖಪುಟ", contactUs: "ಸಂಪರ್ಕಿಸಿ", aboutUs: "ನಮ್ಮ ಬಗ್ಗೆ", siteMap: "ಸೈಟ್ ನಕ್ಷೆ", track: "ಟ್ರ್ಯಾಕ್ ಮಾಡಿ", signIn: "ಸೈನ್ ಇನ್", eyebrow: "ಆಧುನಿಕ ಜನ ಸಮಾಧಾನ AI ಅಹವಾಲು ವೇದಿಕೆ", headline: "ನಾಗರಿಕರು, ಅಧಿಕಾರಿಗಳು ಮತ್ತು ನಿರ್ವಾಹಕರಿಗೆ ಸ್ಮಾರ್ಟ್ ಅಹವಾಲು ಪರಿಹಾರ.", intro: "ಅಹವಾಲು ಸಲ್ಲಿಸಿ, AI ಮೂಲಕ ವರ್ಗೀಕರಿಸಿ, ಸರಿಯಾದ ಅಧಿಕಾರಿಗೆ ಕಳುಹಿಸಿ ಮತ್ತು ಪ್ರಗತಿ ಗಮನಿಸಿ.", add: "ಅಹವಾಲು ಸೇರಿಸಿ", status: "ಸ್ಥಿತಿ ನೋಡಿ", process: "ಪರಿಹಾರ ಪ್ರಕ್ರಿಯೆ", ai: "AI ವರ್ಗೀಕರಣ", officers: "ನೋಡಲ್ / ಅಧಿಕಾರಿಗಳು", assigned: "ಅಹವಾಲು ಹಂಚಿಕೆ", resolved: "ಅಹವಾಲು ಪರಿಹಾರ", assignedPlural: "ಅಹವಾಲುಗಳು ಹಂಚಿಕೆ", rate: "ಪರಿಹಾರ ದರ", preview: "ಲೈವ್ ರೂಟಿಂಗ್ ಪೂರ್ವವೀಕ್ಷಣೆ", workflow: "ಹಂಚಿಕೆ ಕಾರ್ಯಪ್ರವಾಹ", departments: "ವಿಭಾಗಗಳು", levels: "ಅಧಿಕಾರಿ ಮಟ್ಟಗಳು", sla: "SLA ನೋಟ", all: "ಎಲ್ಲಾ", rolePortal: "ಪಾತ್ರ ಆಧಾರಿತ ಪೋರ್ಟಲ್", workspaces: "ನಾಗರಿಕ, ಆಡ್ಮಿನ್ ಮತ್ತು ಅಧಿಕಾರಿ ಕಾರ್ಯಕ್ಷೇತ್ರಗಳು", citizen: "ನಾಗರಿಕ", admin: "ಆಡ್ಮಿನ್ / ಮುಖ್ಯ ಅಧಿಕಾರಿ", officer: "ಅಧಿಕಾರಿ", aiLayer: "AI ಪದರ", aiTitle: "ಪೋರ್ಟಲ್‌ನಲ್ಲಿರುವ ವರ್ಗೀಕರಣ ಎಂಜಿನ್", multilingual: "ಬಹುಭಾಷಿ", routing: "ಸ್ಮಾರ್ಟ್ ರೂಟಿಂಗ್", verified: "ಅಧಿಕಾರಿ ಪರಿಶೀಲಿತ", about: "ಜನ ಸಮಾಧಾನ AI ಬಗ್ಗೆ", contact: "ಸಂಪರ್ಕ", help: "ಪ್ರಶ್ನೆಗಳು / ಸಹಾಯ", footer: "ಜನ ಸಮಾಧಾನ AI | AI ನಾಗರಿಕ ಅಹವಾಲು ಪೋರ್ಟಲ್" }),
  ks: pack({ subtitle: "شہری شکایت انٹیلی جنس پلیٹ فارم", home: "ہوم", contactUs: "رابطہ", aboutUs: "ہمارے بارے میں", siteMap: "سائٹ میپ", track: "ٹریک", signIn: "سائن اِن", eyebrow: "جدید جن سمادھان AI شکایت پلیٹ فارم", headline: "شہریوں، افسروں اور منتظمین کے لئے اسمارٹ شکایت حل۔", intro: "شکایت درج کریں، AI سے درجہ بند کریں، صحیح افسر تک بھیجیں اور پیش رفت دیکھیں۔", add: "شکایت شامل کریں", status: "حالت دیکھیں", process: "حل کا عمل", ai: "AI درجہ بندی", officers: "نوڈل / افسران", assigned: "شکایت تفویض", resolved: "شکایت حل", assignedPlural: "شکایات تفویض", rate: "حل کی شرح", preview: "لائیو روٹنگ پیش نظارہ", workflow: "تفویض ورک فلو", departments: "محکمے", levels: "افسر سطحیں", sla: "SLA منظر", all: "سب", rolePortal: "کردار پر مبنی پورٹل", workspaces: "شہری، ایڈمن اور افسر ورک اسپیس", citizen: "شہری", admin: "ایڈمن / چیف افسر", officer: "افسر", aiLayer: "AI سطح", aiTitle: "پورٹل میں درجہ بندی انجن", multilingual: "کثیر لسانی", routing: "اسمارٹ روٹنگ", verified: "افسر تصدیق شدہ", contact: "رابطہ", help: "مدد", footer: "جن سمادھان AI | AI شہری شکایت پورٹل" }),
  kok: pack({ subtitle: "नागरिक तक्रार बुद्धिमत्ता मंच", home: "मुखेल पान", contactUs: "संपर्क", aboutUs: "आमचें विशीं", siteMap: "साइट नकाशो", track: "ट्रॅक", signIn: "साइन इन", eyebrow: "आधुनिक जन समाधान AI तक्रार मंच", headline: "नागरिक, अधिकारी आनी प्रशासकां खातीर स्मार्ट तक्रार निवारण.", intro: "तक्रार नोंद करात, AI वांगडा वर्गीकृत करात आनी योग्य अधिकार्याक धाडात.", add: "तक्रार जोडात", status: "स्थिती पळयात", process: "निवारण प्रक्रिया", ai: "AI वर्गीकरण", officers: "नोडल / अधिकारी", assigned: "तक्रार सोपयली", resolved: "तक्रार सुटली", assignedPlural: "तक्रारी सोपयल्यो", rate: "निवारण दर", preview: "लाइव्ह रूटिंग पूर्वदर्शन", workflow: "सोपावप कार्यप्रवाह", departments: "विभाग", levels: "अधिकारी स्तर", sla: "SLA दृश्य", all: "सगळें", rolePortal: "भूमिका आधारित पोर्टल", workspaces: "नागरिक, एडमिन आनी अधिकारी कार्यक्षेत्र", citizen: "नागरिक", admin: "एडमिन / मुखेल अधिकारी", officer: "अधिकारी", aiLayer: "AI स्तर", aiTitle: "पोर्टलांतलो वर्गीकरण इंजिन", multilingual: "बहुभाषिक", routing: "स्मार्ट रूटिंग", verified: "अधिकारी सत्यापित", contact: "संपर्क", help: "मदत", footer: "जन समाधान AI | AI नागरिक तक्रार पोर्टल" }),
  mai: pack({ subtitle: "नागरिक शिकायत इंटेलिजेंस प्लेटफॉर्म", home: "घर", contactUs: "संपर्क करू", aboutUs: "हमर बारे मे", siteMap: "साइट मैप", track: "ट्रैक करू", signIn: "साइन इन", eyebrow: "आधुनिक जन समाधान AI शिकायत प्लेटफॉर्म", headline: "नागरिक, अधिकारी आ प्रशासक लेल स्मार्ट शिकायत निवारण।", intro: "शिकायत दर्ज करू, AI सँ वर्गीकृत करू, सही अधिकारी लग पठाउ आ प्रगति देखू।", add: "शिकायत जोड़ू", status: "स्थिति देखू", process: "निवारण प्रक्रिया", ai: "AI वर्गीकरण", officers: "नोडल / अधिकारी", assigned: "शिकायत सौंपल गेल", resolved: "शिकायत हल भेल", assignedPlural: "शिकायत सौंपल गेल", rate: "निवारण दर", preview: "लाइव रूटिंग पूर्वावलोकन", workflow: "असाइनमेंट कार्यप्रवाह", departments: "विभाग", levels: "अधिकारी स्तर", sla: "SLA दृश्य", all: "सभ", rolePortal: "भूमिका आधारित पोर्टल", workspaces: "नागरिक, एडमिन आ अधिकारी कार्यक्षेत्र", citizen: "नागरिक", admin: "एडमिन / मुख्य अधिकारी", officer: "अधिकारी", aiLayer: "AI परत", aiTitle: "पोर्टल मे बनल वर्गीकरण इंजन", multilingual: "बहुभाषी", routing: "स्मार्ट रूटिंग", verified: "अधिकारी सत्यापित", contact: "संपर्क", help: "सहायता", footer: "जन समाधान AI | AI नागरिक शिकायत पोर्टल" }),
  ml: pack({ subtitle: "പൗര പരാതി ഇന്റലിജൻസ് പ്ലാറ്റ്ഫോം", home: "ഹോം", contactUs: "ബന്ധപ്പെടുക", aboutUs: "ഞങ്ങളെ കുറിച്ച്", siteMap: "സൈറ്റ് മാപ്പ്", track: "ട്രാക്ക്", signIn: "സൈൻ ഇൻ", eyebrow: "ആധുനിക ജന സമാധാൻ AI പരാതി പ്ലാറ്റ്ഫോം", headline: "പൗരന്മാർക്കും ഉദ്യോഗസ്ഥർക്കും ഭരണകർത്താക്കൾക്കും സ്മാർട്ട് പരാതി പരിഹാരം.", intro: "പരാതി നൽകുക, AI ഉപയോഗിച്ച് വർഗീകരിക്കുക, ശരിയായ അധികാരിയിലേക്ക് അയയ്ക്കുക, പുരോഗതി നിരീക്ഷിക്കുക.", add: "പരാതി ചേർക്കുക", status: "സ്ഥിതി കാണുക", process: "പരിഹാര പ്രക്രിയ", ai: "AI വർഗീകരണം", officers: "നോഡൽ / ഉദ്യോഗസ്ഥർ", assigned: "പരാതി നിയോഗിച്ചു", resolved: "പരാതി പരിഹരിച്ചു", assignedPlural: "പരാതികൾ നിയോഗിച്ചു", rate: "പരിഹാര നിരക്ക്", preview: "ലൈവ് റൂട്ടിംഗ് പ്രിവ്യൂ", workflow: "നിയോഗ പ്രവർത്തനക്രമം", departments: "വകുപ്പുകൾ", levels: "ഉദ്യോഗസ്ഥ തലങ്ങൾ", sla: "SLA കാഴ്ച", all: "എല്ലാം", rolePortal: "റോൾ അടിസ്ഥാന പോർട്ടൽ", workspaces: "പൗരൻ, അഡ്മിൻ, ഉദ്യോഗസ്ഥൻ വർക്ക്‌സ്‌പേസുകൾ", citizen: "പൗരൻ", admin: "അഡ്മിൻ / പ്രധാന ഉദ്യോഗസ്ഥൻ", officer: "ഉദ്യോഗസ്ഥൻ", aiLayer: "AI ലെയർ", aiTitle: "പോർട്ടലിൽ നിർമ്മിച്ച വർഗീകരണ എഞ്ചിൻ", multilingual: "ബഹുഭാഷ", routing: "സ്മാർട്ട് റൂട്ടിംഗ്", verified: "ഉദ്യോഗസ്ഥൻ സ്ഥിരീകരിച്ചു", contact: "ബന്ധപ്പെടുക", help: "സഹായം", footer: "ജന സമാധാൻ AI | AI പൗര പരാതി പോർട്ടൽ" }),
  mni: pack({ subtitle: "নাগরিক অভিযোগ ইন্টেলিজেন্স প্ল্যাটফর্ম", home: "হোম", contactUs: "যোগাযোগ", aboutUs: "আমাদের সম্পর্কে", siteMap: "সাইট ম্যাপ", track: "ট্র্যাক", signIn: "সাইন ইন", eyebrow: "আধুনিক জন সমাধান AI অভিযোগ প্ল্যাটফর্ম", headline: "নাগরিক, অফিসার ও প্রশাসকের জন্য স্মার্ট অভিযোগ সমাধান।", intro: "অভিযোগ জমা দিন, AI দিয়ে শ্রেণীবিভাগ করুন ও সঠিক কর্তৃপক্ষকে পাঠান।", add: "অভিযোগ যোগ করুন", status: "স্থিতি দেখুন", process: "সমাধান প্রক্রিয়া", ai: "AI শ্রেণীবিভাগ", officers: "নোডাল / অফিসার", assigned: "অভিযোগ বরাদ্দ", resolved: "অভিযোগ সমাধান", assignedPlural: "অভিযোগ বরাদ্দ", rate: "সমাধান হার", preview: "লাইভ রাউটিং প্রিভিউ", workflow: "বরাদ্দ কর্মপ্রবাহ", departments: "বিভাগ", levels: "অফিসার স্তর", sla: "SLA দৃশ্য", all: "সব", rolePortal: "ভূমিকা ভিত্তিক পোর্টাল", workspaces: "নাগরিক, অ্যাডমিন ও অফিসার কর্মক্ষেত্র", citizen: "নাগরিক", admin: "অ্যাডমিন / প্রধান অফিসার", officer: "অফিসার", aiLayer: "AI স্তর", aiTitle: "পোর্টালের শ্রেণীবিভাগ ইঞ্জিন", multilingual: "বহুভাষিক", routing: "স্মার্ট রাউটিং", verified: "অফিসার যাচাইকৃত", contact: "যোগাযোগ", help: "সহায়তা", footer: "জন সমাধান AI | AI নাগরিক অভিযোগ পোর্টাল" }),
  mr: pack({ subtitle: "नागरिक तक्रार इंटेलिजन्स प्लॅटफॉर्म", home: "मुख्यपृष्ठ", contactUs: "संपर्क करा", aboutUs: "आमच्याबद्दल", siteMap: "साइट मॅप", track: "ट्रॅक करा", signIn: "साइन इन", eyebrow: "आधुनिक जन समाधान AI तक्रार प्लॅटफॉर्म", headline: "नागरिक, अधिकारी आणि प्रशासकांसाठी स्मार्ट तक्रार निवारण.", intro: "तक्रार नोंदवा, AI ने वर्गीकृत करा, योग्य अधिकाऱ्याकडे पाठवा आणि प्रगती पहा.", add: "तक्रार जोडा", status: "स्थिती पहा", process: "निवारण प्रक्रिया", ai: "AI वर्गीकरण", officers: "नोडल / अधिकारी", assigned: "तक्रार सोपवली", resolved: "तक्रार सुटली", assignedPlural: "तक्रारी सोपवल्या", rate: "निवारण दर", preview: "लाइव्ह रूटिंग पूर्वावलोकन", workflow: "सोपवणी कार्यप्रवाह", departments: "विभाग", levels: "अधिकारी स्तर", sla: "SLA दृश्य", all: "सर्व", rolePortal: "भूमिका-आधारित पोर्टल", workspaces: "नागरिक, अ‍ॅडमिन आणि अधिकारी कार्यक्षेत्र", citizen: "नागरिक", admin: "अ‍ॅडमिन / मुख्य अधिकारी", officer: "अधिकारी", aiLayer: "AI स्तर", aiTitle: "पोर्टलमधील वर्गीकरण इंजिन", multilingual: "बहुभाषिक", routing: "स्मार्ट रूटिंग", verified: "अधिकारी सत्यापित", contact: "संपर्क", help: "मदत", footer: "जन समाधान AI | AI नागरिक तक्रार पोर्टल" }),
  ne: pack({ subtitle: "नागरिक गुनासो इन्टेलिजेन्स प्लेटफर्म", home: "गृह", contactUs: "सम्पर्क", aboutUs: "हाम्रो बारेमा", siteMap: "साइट म्याप", track: "ट्र्याक", signIn: "साइन इन", eyebrow: "आधुनिक जन समाधान AI गुनासो प्लेटफर्म", headline: "नागरिक, अधिकारी र प्रशासकका लागि स्मार्ट गुनासो समाधान।", intro: "गुनासो दर्ता गर्नुहोस्, AI बाट वर्गीकरण गर्नुहोस्, सही अधिकारीसम्म पठाउनुहोस् र प्रगति हेर्नुहोस्।", add: "गुनासो थप्नुहोस्", status: "स्थिति हेर्नुहोस्", process: "समाधान प्रक्रिया", ai: "AI वर्गीकरण", officers: "नोडल / अधिकारी", assigned: "गुनासो तोकियो", resolved: "गुनासो समाधान", assignedPlural: "गुनासाहरू तोकिए", rate: "समाधान दर", preview: "लाइभ राउटिङ पूर्वावलोकन", workflow: "तोकाइ कार्यप्रवाह", departments: "विभागहरू", levels: "अधिकारी स्तर", sla: "SLA दृश्य", all: "सबै", rolePortal: "भूमिका आधारित पोर्टल", workspaces: "नागरिक, एडमिन र अधिकारी कार्यक्षेत्र", citizen: "नागरिक", admin: "एडमिन / मुख्य अधिकारी", officer: "अधिकारी", aiLayer: "AI तह", aiTitle: "पोर्टलमा निर्मित वर्गीकरण इन्जिन", multilingual: "बहुभाषी", routing: "स्मार्ट राउटिङ", verified: "अधिकारी प्रमाणित", contact: "सम्पर्क", help: "सहायता", footer: "जन समाधान AI | AI नागरिक गुनासो पोर्टल" }),
  or: pack({ subtitle: "ନାଗରିକ ଅଭିଯୋଗ ଇଣ୍ଟେଲିଜେନ୍ସ ପ୍ଲାଟଫର୍ମ", home: "ହୋମ", contactUs: "ଯୋଗାଯୋଗ", aboutUs: "ଆମ ବିଷୟରେ", siteMap: "ସାଇଟ ମ୍ୟାପ", track: "ଟ୍ରାକ", signIn: "ସାଇନ ଇନ", eyebrow: "ଆଧୁନିକ ଜନ ସମାଧାନ AI ଅଭିଯୋଗ ପ୍ଲାଟଫର୍ମ", headline: "ନାଗରିକ, ଅଧିକାରୀ ଓ ପ୍ରଶାସକଙ୍କ ପାଇଁ ସ୍ମାର୍ଟ ଅଭିଯୋଗ ସମାଧାନ।", intro: "ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ, AI ଦ୍ୱାରା ବର୍ଗୀକରଣ କରନ୍ତୁ, ଠିକ ଅଧିକାରୀଙ୍କୁ ପଠାନ୍ତୁ ଓ ପ୍ରଗତି ଦେଖନ୍ତୁ।", add: "ଅଭିଯୋଗ ଯୋଡନ୍ତୁ", status: "ସ୍ଥିତି ଦେଖନ୍ତୁ", process: "ସମାଧାନ ପ୍ରକ୍ରିୟା", ai: "AI ବର୍ଗୀକରଣ", officers: "ନୋଡାଲ / ଅଧିକାରୀ", assigned: "ଅଭିଯୋଗ ଦିଆଗଲା", resolved: "ଅଭିଯୋଗ ସମାଧାନ", assignedPlural: "ଅଭିଯୋଗ ଦିଆଗଲା", rate: "ସମାଧାନ ହାର", preview: "ଲାଇଭ ରାଉଟିଂ ପ୍ରିଭ୍ୟୁ", workflow: "ବଣ୍ଟନ କାର୍ଯ୍ୟପ୍ରବାହ", departments: "ବିଭାଗ", levels: "ଅଧିକାରୀ ସ୍ତର", sla: "SLA ଦୃଶ୍ୟ", all: "ସମସ୍ତ", rolePortal: "ଭୂମିକା ଆଧାରିତ ପୋର୍ଟାଲ", workspaces: "ନାଗରିକ, ଆଡମିନ ଓ ଅଧିକାରୀ କାର୍ଯ୍ୟକ୍ଷେତ୍ର", citizen: "ନାଗରିକ", admin: "ଆଡମିନ / ମୁଖ୍ୟ ଅଧିକାରୀ", officer: "ଅଧିକାରୀ", aiLayer: "AI ସ୍ତର", aiTitle: "ପୋର୍ଟାଲରେ ଥିବା ବର୍ଗୀକରଣ ଇଞ୍ଜିନ", multilingual: "ବହୁଭାଷୀ", routing: "ସ୍ମାର୍ଟ ରାଉଟିଂ", verified: "ଅଧିକାରୀ ସତ୍ୟାପିତ", contact: "ଯୋଗାଯୋଗ", help: "ସହାୟତା", footer: "ଜନ ସମାଧାନ AI | AI ନାଗରିକ ଅଭିଯୋଗ ପୋର୍ଟାଲ" }),
  pa: pack({ subtitle: "ਨਾਗਰਿਕ ਸ਼ਿਕਾਇਤ ਇੰਟੈਲੀਜੈਂਸ ਪਲੇਟਫਾਰਮ", home: "ਹੋਮ", contactUs: "ਸੰਪਰਕ ਕਰੋ", aboutUs: "ਸਾਡੇ ਬਾਰੇ", siteMap: "ਸਾਈਟ ਮੈਪ", track: "ਟ੍ਰੈਕ ਕਰੋ", signIn: "ਸਾਈਨ ਇਨ", eyebrow: "ਆਧੁਨਿਕ ਜਨ ਸਮਾਧਾਨ AI ਸ਼ਿਕਾਇਤ ਪਲੇਟਫਾਰਮ", headline: "ਨਾਗਰਿਕਾਂ, ਅਧਿਕਾਰੀਆਂ ਅਤੇ ਪ੍ਰਸ਼ਾਸਕਾਂ ਲਈ ਸਮਾਰਟ ਸ਼ਿਕਾਇਤ ਨਿਵਾਰਣ।", intro: "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ, AI ਨਾਲ ਵਰਗੀਕਰਨ ਕਰੋ, ਸਹੀ ਅਧਿਕਾਰੀ ਨੂੰ ਭੇਜੋ ਅਤੇ ਤਰੱਕੀ ਦੇਖੋ।", add: "ਸ਼ਿਕਾਇਤ ਜੋੜੋ", status: "ਸਥਿਤੀ ਵੇਖੋ", process: "ਨਿਵਾਰਣ ਪ੍ਰਕਿਰਿਆ", ai: "AI ਵਰਗੀਕਰਨ", officers: "ਨੋਡਲ / ਅਧਿਕਾਰੀ", assigned: "ਸ਼ਿਕਾਇਤ ਸੌਂਪੀ ਗਈ", resolved: "ਸ਼ਿਕਾਇਤ ਹੱਲ ਹੋਈ", assignedPlural: "ਸ਼ਿਕਾਇਤਾਂ ਸੌਂਪੀਆਂ ਗਈਆਂ", rate: "ਹੱਲ ਦਰ", preview: "ਲਾਈਵ ਰੂਟਿੰਗ ਪ੍ਰੀਵਿਊ", workflow: "ਸੌਂਪਣ ਕਾਰਜ-ਪ੍ਰਵਾਹ", departments: "ਵਿਭਾਗ", levels: "ਅਧਿਕਾਰੀ ਪੱਧਰ", sla: "SLA ਦ੍ਰਿਸ਼", all: "ਸਭ", rolePortal: "ਭੂਮਿਕਾ-ਆਧਾਰਿਤ ਪੋਰਟਲ", workspaces: "ਨਾਗਰਿਕ, ਐਡਮਿਨ ਅਤੇ ਅਧਿਕਾਰੀ ਵਰਕਸਪੇਸ", citizen: "ਨਾਗਰਿਕ", admin: "ਐਡਮਿਨ / ਮੁੱਖ ਅਧਿਕਾਰੀ", officer: "ਅਧਿਕਾਰੀ", aiLayer: "AI ਪਰਤ", aiTitle: "ਪੋਰਟਲ ਵਿੱਚ ਬਣਿਆ ਵਰਗੀਕਰਨ ਇੰਜਨ", multilingual: "ਬਹੁਭਾਸ਼ੀ", routing: "ਸਮਾਰਟ ਰੂਟਿੰਗ", verified: "ਅਧਿਕਾਰੀ ਪ੍ਰਮਾਣਿਤ", contact: "ਸੰਪਰਕ", help: "ਮਦਦ", footer: "ਜਨ ਸਮਾਧਾਨ AI | AI ਨਾਗਰਿਕ ਸ਼ਿਕਾਇਤ ਪੋਰਟਲ" }),
  sa: pack({ subtitle: "नागरिक-अभियोग-बुद्धिमत्ता-मञ्चः", home: "गृहम्", contactUs: "सम्पर्कः", aboutUs: "अस्माकं विषये", siteMap: "स्थल-मानचित्रम्", track: "अनुसरणम्", signIn: "प्रवेशः", eyebrow: "आधुनिकः जन समाधान AI अभियोग-मञ्चः", headline: "नागरिकाणां, अधिकारिणां प्रशासकानां च कृते स्मार्ट अभियोग-निवारणम्।", intro: "अभियोगं ददातु, AI द्वारा वर्गीकुरुत, योग्याधिकारिणे प्रेषयत, प्रगतिं पश्यत।", add: "अभियोगं योजयत", status: "स्थितिं पश्यत", process: "निवारण-प्रक्रिया", ai: "AI वर्गीकरणम्", officers: "नोडल / अधिकारी", assigned: "अभियोगः नियुक्तः", resolved: "अभियोगः निराकृतः", assignedPlural: "अभियोगाः नियुक्ताः", rate: "निवारण-दरः", preview: "सजीव-मार्गण-पूर्वदर्शनम्", workflow: "नियोजन-कार्यप्रवाहः", departments: "विभागाः", levels: "अधिकारी-स्तराः", sla: "SLA दर्शनम्", all: "सर्वे", rolePortal: "भूमिका-आधारितः पोर्टलः", workspaces: "नागरिक-प्रशासक-अधिकारी कार्यक्षेत्राणि", citizen: "नागरिकः", admin: "प्रशासकः / मुख्याधिकारी", officer: "अधिकारी", aiLayer: "AI स्तरः", aiTitle: "पोर्टले निर्मितं वर्गीकरण-यन्त्रम्", multilingual: "बहुभाषिकम्", routing: "स्मार्ट मार्गणम्", verified: "अधिकारी सत्यापितः", contact: "सम्पर्कः", help: "सहाय्यम्", footer: "जन समाधान AI | AI नागरिक अभियोग पोर्टलः" }),
  sat: pack({ subtitle: "ᱱᱟᱜᱟᱨᱤᱠ ᱚᱵᱷᱤᱡᱚᱜ ᱵᱩᱫᱽᱫᱷᱤ ᱯᱞᱮᱴᱯᱷᱚᱨᱢ", home: "ᱚᱲᱟᱜ", contactUs: "ᱡᱚᱜᱟᱡᱚᱜ", aboutUs: "ᱟᱞᱮ ᱵᱟᱵᱚᱛ", siteMap: "ᱥᱟᱭᱤᱴ ᱢᱮᱯ", track: "ᱴᱨᱮᱠ", signIn: "ᱥᱟᱭᱤᱱ ᱤᱱ", eyebrow: "ᱟᱫᱷᱩᱱᱤᱠ ᱡᱚᱱ ᱥᱚᱢᱟᱫᱷᱟᱱ AI ᱚᱵᱷᱤᱡᱚᱜ ᱯᱞᱮᱴᱯᱷᱚᱨᱢ", headline: "ᱱᱟᱜᱟᱨᱤᱠ, ᱚᱯᱷᱤᱥᱟᱨ ᱟᱨ ᱯᱨᱚᱥᱟᱥᱚᱠ ᱞᱟᱹᱜᱤᱫ ᱥᱢᱟᱨᱴ ᱚᱵᱷᱤᱡᱚᱜ ᱥᱚᱢᱟᱫᱷᱟᱱ।", intro: "ᱚᱵᱷᱤᱡᱚᱜ ᱡᱚᱢᱟ ᱢᱮ, AI ᱥᱟᱶ ᱵᱷᱟᱜ ᱢᱮ, ᱴᱷᱤᱠ ᱚᱯᱷᱤᱥᱟᱨ ᱴᱷᱮᱱ ᱯᱟᱴᱷᱟᱣ ᱢᱮ।", add: "ᱚᱵᱷᱤᱡᱚᱜ ᱥᱮᱞᱮᱫ", status: "ᱥᱛᱷᱤᱛᱤ ᱧᱮᱞ", process: "ᱥᱚᱢᱟᱫᱷᱟᱱ ᱯᱨᱚᱠᱨᱤᱭᱟ", ai: "AI ᱵᱷᱟᱜ", officers: "ᱱᱚᱰᱟᱞ / ᱚᱯᱷᱤᱥᱟᱨ", assigned: "ᱚᱵᱷᱤᱡᱚᱜ ᱵᱟᱴᱟᱣ", resolved: "ᱚᱵᱷᱤᱡᱚᱜ ᱥᱚᱢᱟᱫᱷᱟᱱ", assignedPlural: "ᱚᱵᱷᱤᱡᱚᱜ ᱵᱟᱴᱟᱣ", rate: "ᱥᱚᱢᱟᱫᱷᱟᱱ ᱫᱚᱨ", departments: "ᱵᱤᱵᱷᱟᱜ", all: "ᱡᱷᱚᱛᱚ", citizen: "ᱱᱟᱜᱟᱨᱤᱠ", admin: "ᱮᱰᱢᱤᱱ / ᱢᱩᱬ ᱚᱯᱷᱤᱥᱟᱨ", officer: "ᱚᱯᱷᱤᱥᱟᱨ", multilingual: "ᱵᱟᱹᱲᱛᱤ ᱯᱟᱹᱨᱥᱤ", contact: "ᱡᱚᱜᱟᱡᱚᱜ", help: "ᱜᱚᱲᱚ", footer: "ᱡᱚᱱ ᱥᱚᱢᱟᱫᱷᱟᱱ AI | AI ᱱᱟᱜᱟᱨᱤᱠ ᱚᱵᱷᱤᱡᱚᱜ ᱯᱚᱨᱴᱟᱞ" }),
  sd: pack({ subtitle: "شهري شڪايت انٽيليجنس پليٽفارم", home: "هوم", contactUs: "رابطو", aboutUs: "اسان بابت", siteMap: "سائيٽ ميپ", track: "ٽريڪ", signIn: "سائن اِن", eyebrow: "جديد جن سمادھان AI شڪايت پليٽفارم", headline: "شهرين، آفيسرن ۽ منتظمن لاءِ سمارٽ شڪايت حل.", intro: "شڪايت داخل ڪريو، AI سان درجا بندي ڪريو، صحيح آفيسر ڏانهن موڪليو ۽ اڳڀرائي ڏسو.", add: "شڪايت شامل ڪريو", status: "حالت ڏسو", process: "حل جو عمل", ai: "AI درجا بندي", officers: "نوڊل / آفيسر", assigned: "شڪايت ڏني وئي", resolved: "شڪايت حل ٿي", assignedPlural: "شڪايتون ڏنيون ويون", rate: "حل جي شرح", preview: "لائيو روٽنگ ڏيک", workflow: "تفويض ڪم فلو", departments: "کاتا", levels: "آفيسر سطحون", sla: "SLA ڏيک", all: "سڀ", rolePortal: "ڪردار تي ٻڌل پورٽل", workspaces: "شهري، ايڊمن ۽ آفيسر ڪم جڳهون", citizen: "شهري", admin: "ايڊمن / مکيه آفيسر", officer: "آفيسر", aiLayer: "AI سطح", aiTitle: "پورٽل ۾ درجا بندي انجڻ", multilingual: "گهڻ ٻولي", routing: "سمارٽ روٽنگ", verified: "آفيسر تصديق ٿيل", contact: "رابطو", help: "مدد", footer: "جن سمادھان AI | AI شهري شڪايت پورٽل" }),
  ta: pack({ subtitle: "குடிமக்கள் குறைதீர் நுண்ணறிவு தளம்", home: "முகப்பு", contactUs: "தொடர்பு கொள்ளுங்கள்", aboutUs: "எங்களை பற்றி", siteMap: "தள வரைபடம்", track: "கண்காணிக்க", signIn: "உள்நுழை", eyebrow: "நவீன Jan Samadhan AI குறைதீர் தளம்", headline: "குடிமக்கள், அதிகாரிகள் மற்றும் நிர்வாகிகளுக்கான ச்மார்ட் குறைதீர்.", intro: "குறையை பதிவு செய்யுங்கள், AI மூலம் வகைப்படுத்துங்கள், சரியான அதிகாரிக்கு அனுப்பி முன்னேற்றத்தை பார்க்கவும்.", add: "குறையைச் சேர்க்க", status: "நிலையைப் பார்க்க", process: "குறைதீர் செயல்முறை", ai: "AI வகைப்பாடு", officers: "நோடல் / அதிகாரிகள்", assigned: "குறை ஒதுக்கப்பட்டது", resolved: "குறை தீர்க்கப்பட்டது", assignedPlural: "குறைகள் ஒதுக்கப்பட்டன", rate: "தீர்வு விகிதம்", preview: "நேரடி வழிமுறை முன்னோட்டம்", workflow: "ஒதுக்கீட்டு பணிச்சூழல்", departments: "துறைகள்", levels: "அதிகாரி நிலைகள்", sla: "SLA காட்சி", all: "அனைத்தும்", rolePortal: "பங்கு அடிப்படையிலான தளம்", workspaces: "குடிமக்கள், நிர்வாகி மற்றும் அதிகாரி பணிமூலங்கள்", citizen: "குடிமகன்", admin: "நிர்வாகி / முதன்மை அதிகாரி", officer: "அதிகாரி", aiLayer: "AI அடுக்கு", aiTitle: "தளத்தில் கட்டப்பட்ட வகைப்பாடு இயந்திரம்", multilingual: "பலமொழி", routing: "ச்மார்ட் வழிமுறை", verified: "அதிகாரி சரிபார்த்தது", contact: "தொடர்பு", help: "கேள்விகள் / உதவி", footer: "Jan Samadhan AI | AI குடிமக்கள் குறைதீர் தளம்" }),
  te: pack({ subtitle: "పౌర ఫిర్యాదు ఇంటెలిజెన్స్ ప్లాట్‌ఫారమ్", home: "హోమ్", contactUs: "సంప్రదించండి", aboutUs: "మా గురించి", siteMap: "సైట్ మ్యాప్", track: "ట్రాక్", signIn: "సైన్ ఇన్", eyebrow: "ఆధునిక Jan Samadhan AI ఫిర్యాదు ప్లాట్‌ఫారమ్", headline: "పౌరులు, అధికారులు మరియు నిర్వాహకుల కోసం స్మార్ట్ ఫిర్యాదు పరిష్కారం.", intro: "ఫిర్యాదు నమోదు చేయండి, AI తో వర్గీకరించండి, సరైన అధికారికి పంపండి మరియు పురోగతిని చూడండి.", add: "ఫిర్యాదు జోడించండి", status: "స్థితి చూడండి", process: "పరిష్కార ప్రక్రియ", ai: "AI వర్గీకరణ", officers: "నోడల్ / అధికారులు", assigned: "ఫిర్యాదు కేటాయించబడింది", resolved: "ఫిర్యాదు పరిష్కరించబడింది", assignedPlural: "ఫిర్యాదులు కేటాయించబడ్డాయి", rate: "పరిష్కార రేటు", preview: "లైవ్ రూటింగ్ ప్రివ్యూ", workflow: "కేటాయింపు పనిప్రవాహం", departments: "శాఖలు", levels: "అధికారి స్థాయులు", sla: "SLA వీక్షణ", all: "అన్నీ", rolePortal: "పాత్ర ఆధారిత పోర్టల్", workspaces: "పౌరుడు, అడ్మిన్ మరియు అధికారి వర్క్‌స్పేస్‌లు", citizen: "పౌరుడు", admin: "అడ్మిన్ / ప్రధాన అధికారి", officer: "అధికారి", aiLayer: "AI పొర", aiTitle: "పోర్టల్‌లో నిర్మించిన వర్గీకరణ ఇంజిన్", multilingual: "బహుభాషా", routing: "స్మార్ట్ రూటింగ్", verified: "అధికారి ధృవీకరించారు", contact: "సంప్రదించండి", help: "సహాయం", footer: "Jan Samadhan AI | AI పౌర ఫిర్యాదు పోర్టల్" }),
  ur: pack({ subtitle: "شہری شکایت انٹیلی جنس پلیٹ فارم", home: "ہوم", contactUs: "رابطہ کریں", aboutUs: "ہمارے بارے میں", siteMap: "سائٹ میپ", track: "ٹریک کریں", signIn: "سائن اِن", eyebrow: "جدید جن سمادھان AI شکایت پلیٹ فارم", headline: "شہریوں، افسروں اور منتظمین کے لئے اسمارٹ شکایت ازالہ۔", intro: "شکایت درج کریں، AI سے درجہ بند کریں، صحیح اتھارٹی کو بھیجیں اور پیش رفت دیکھیں۔", add: "شکایت شامل کریں", status: "حالت دیکھیں", process: "ازالہ عمل", ai: "AI درجہ بندی", officers: "نوڈل / افسران", assigned: "شکایت تفویض", resolved: "شکایت حل", assignedPlural: "شکایات تفویض", rate: "حل کی شرح", preview: "لائیو روٹنگ پیش نظارہ", workflow: "تفویض ورک فلو", departments: "محکمے", levels: "افسر سطحیں", sla: "SLA منظر", all: "سب", rolePortal: "کردار پر مبنی پورٹل", workspaces: "شہری، ایڈمن اور افسر ورک اسپیس", citizen: "شہری", admin: "ایڈمن / مرکزی افسر", officer: "افسر", aiLayer: "AI پرت", aiTitle: "پورٹل میں بنایا گیا درجہ بندی انجن", multilingual: "کثیر لسانی", routing: "اسمارٹ روٹنگ", verified: "افسر تصدیق شدہ", contact: "رابطہ", help: "مدد", footer: "جن سمادھان AI | AI شہری شکایت پورٹل" }),
};

const dashboardTranslations = {
  hi: {
    "Officer Workspace": "अधिकारी कार्यक्षेत्र",
    "Main Officer Dashboard": "मुख्य अधिकारी डैशबोर्ड",
    "Officer Dashboard": "अधिकारी डैशबोर्ड",
    "Sub Officer Dashboard": "उप अधिकारी डैशबोर्ड",
    "Field Officer Dashboard": "फील्ड अधिकारी डैशबोर्ड",
    "Citizen Dashboard": "नागरिक डैशबोर्ड",
    "My Complaints": "मेरी शिकायतें",
    "Welcome,": "स्वागत है,",
    "Submit, track, and rate grievances from one place.": "एक ही जगह से शिकायत दर्ज करें, ट्रैक करें और रेटिंग दें।",
    "New Complaint": "नई शिकायत",
    "Submit New Complaint": "नई शिकायत जमा करें",
    "AI will classify and route it after submission.": "जमा करने के बाद AI इसे वर्गीकृत कर सही अधिकारी तक भेजेगा।",
    "Total Complaints": "कुल शिकायतें",
    "Total Assigned": "कुल सौंपी गई",
    "Pending": "लंबित",
    "In Progress": "प्रगति में",
    "Resolved": "हल हुई",
    "Escalated": "आगे बढ़ाई गई",
    "Active": "सक्रिय",
    "All": "सभी",
    "Add Complaint": "शिकायत जोड़ें",
    "Complaint Management": "शिकायत प्रबंधन",
    "Complaint Status": "शिकायत स्थिति",
    "Complaint List": "शिकायत सूची",
    "Update Complaint": "शिकायत अपडेट करें",
    "Resolution Report": "समाधान रिपोर्ट",
    "Assign Officer": "अधिकारी नियुक्त करें",
    "Assign Senior Officer": "वरिष्ठ अधिकारी नियुक्त करें",
    "Assign Sub Officer": "उप अधिकारी नियुक्त करें",
    "Assign Field Officer": "फील्ड अधिकारी नियुक्त करें",
    "Add, Edit, Delete Senior Officers": "वरिष्ठ अधिकारी जोड़ें, संपादित करें, हटाएं",
    "Add, Edit, Delete Sub Officers": "उप अधिकारी जोड़ें, संपादित करें, हटाएं",
    "Add, Edit, Delete Field Officers": "फील्ड अधिकारी जोड़ें, संपादित करें, हटाएं",
    "First Name": "पहला नाम",
    "Last Name": "अंतिम नाम",
    "Username": "उपयोगकर्ता नाम",
    "Email": "ईमेल",
    "Phone": "फोन",
    "Employee ID": "कर्मचारी ID",
    "Area / Region": "क्षेत्र / इलाका",
    "Sector / Ward": "सेक्टर / वार्ड",
    "PIN Code": "पिन कोड",
    "Password": "पासवर्ड",
    "Password unchanged": "पासवर्ड नहीं बदलेगा",
    "Senior Officer": "वरिष्ठ अधिकारी",
    "Sub Officer": "उप अधिकारी",
    "Field Officer": "फील्ड अधिकारी",
    "Department-Wise Main Officer": "विभागीय मुख्य अधिकारी",
    "Sub-Section / Field Officer": "उप-खंड / फील्ड अधिकारी",
    "Department Officer": "विभाग अधिकारी",
    "Department": "विभाग",
    "Electricity Department": "बिजली विभाग",
    "Water Supply Department": "जल आपूर्ति विभाग",
    "Sanitation Department": "स्वच्छता विभाग",
    "Roads & Infrastructure": "सड़क और आधारभूत संरचना विभाग",
    "Public Services": "लोक सेवा विभाग",
    "Health Department": "स्वास्थ्य विभाग",
    "Education Department": "शिक्षा विभाग",
    "General / Other": "सामान्य / अन्य",
    "Add Officer": "अधिकारी जोड़ें",
    "Save Officer": "अधिकारी सहेजें",
    "Edit": "संपादित करें",
    "Delete": "हटाएं",
    "Cancel": "रद्द करें",
    "No area": "कोई क्षेत्र नहीं",
    "Complaint title": "शिकायत शीर्षक",
    "Complaint details": "शिकायत विवरण",
    "Location": "स्थान",
    "Adding...": "जोड़ा जा रहा है...",
    "all": "सभी",
    "active": "सक्रिय",
    "resolved": "हल हुई",
    "escalated": "आगे बढ़ाई गई",
    "No complaints here": "यहां कोई शिकायत नहीं है",
    "Check another filter tab.": "दूसरा फिल्टर टैब देखें।",
    "Update": "अपडेट करें",
    "Last update": "अंतिम अपडेट",
    "Update Status": "स्थिति अपडेट करें",
    "Assign to Senior Officer": "वरिष्ठ अधिकारी को सौंपें",
    "Assign to Sub Officer": "उप अधिकारी को सौंपें",
    "Assign to Field Officer": "फील्ड अधिकारी को सौंपें",
    "Forward Complaint": "शिकायत आगे भेजें",
    "Keep with me": "मेरे पास रखें",
    "Nearest:": "निकटतम:",
    "Assign nearest by area / PIN": "क्षेत्र / पिन के अनुसार निकटतम को सौंपें",
    "Upload Proof": "प्रमाण अपलोड करें",
    "Officer Remarks": "अधिकारी टिप्पणी",
    "Describe action taken, findings, or reason...": "की गई कार्रवाई, निष्कर्ष या कारण लिखें...",
    "Saving...": "सहेजा जा रहा है...",
    "Save Update": "अपडेट सहेजें",
    "View proof of resolution": "समाधान प्रमाण देखें",
    "SLA Breached": "SLA उल्लंघन",
    "SLA": "SLA",
    "AI": "AI",
    "Citizen": "नागरिक",
    "Valid ID": "मान्य ID",
    "Area": "क्षेत्र",
    "Officer": "अधिकारी",
    "Officer remarks": "अधिकारी टिप्पणी",
    "Citizen Name": "नागरिक का नाम",
    "Full name of complainant": "शिकायतकर्ता का पूरा नाम",
    "Valid ID Number": "मान्य ID नंबर",
    "Aadhaar / Voter ID / PAN / local ID": "आधार / वोटर ID / PAN / स्थानीय ID",
    "Title": "शीर्षक",
    "Brief title of your complaint": "अपनी शिकायत का छोटा शीर्षक",
    "Description": "विवरण",
    "Hindi or English both accepted": "हिंदी या अंग्रेजी दोनों स्वीकार हैं",
    "Describe your complaint in detail. AI will auto-classify it.": "अपनी शिकायत विस्तार से लिखें। AI इसे अपने आप वर्गीकृत करेगा।",
    "Location / Address": "स्थान / पता",
    "Ward no., area, city": "वार्ड नंबर, क्षेत्र, शहर",
    "Sector 4 or Ward 12": "सेक्टर 4 या वार्ड 12",
    "Complaint File / Picture": "शिकायत फ़ाइल / फोटो",
    "Submitting...": "जमा किया जा रहा है...",
    "Submit Complaint": "शिकायत जमा करें",
    "No complaints yet": "अभी कोई शिकायत नहीं",
    "Submit your first complaint and we'll route it to the right department.": "अपनी पहली शिकायत जमा करें, हम उसे सही विभाग तक भेजेंगे।",
    "AI Category": "AI श्रेणी",
    "SLA Deadline": "SLA अंतिम समय",
    "Rate your experience:": "अपने अनुभव को रेट करें:",
    "Any comments?": "कोई टिप्पणी?",
    "Submit Feedback": "फीडबैक जमा करें",
    "Complaint submitted! AI is classifying it now.": "शिकायत जमा हो गई! AI अभी इसे वर्गीकृत कर रहा है।",
    "Submission failed": "जमा करना विफल रहा",
    "Thank you for your feedback!": "आपके फीडबैक के लिए धन्यवाद!",
    "Complaint updated!": "शिकायत अपडेट हुई!",
    "Update failed": "अपडेट विफल",
    "Officer updated": "अधिकारी अपडेट हुआ",
    "Officer added": "अधिकारी जोड़ा गया",
    "Officer deleted": "अधिकारी हटाया गया",
    "Delete failed": "हटाना विफल",
    "Officer save failed": "अधिकारी सहेजना विफल",
    "Complaint added": "शिकायत जोड़ी गई",
    "Complaint add failed": "शिकायत जोड़ना विफल",
    "PENDING": "लंबित",
    "ASSIGNED": "सौंपी गई",
    "IN PROGRESS": "प्रगति में",
    "IN_PROGRESS": "प्रगति में",
    "RESOLVED": "हल हुई",
    "CLOSED": "बंद",
    "ESCALATED": "आगे बढ़ाई गई",
    "REJECTED": "अस्वीकृत",
    "LOW": "कम",
    "MEDIUM": "मध्यम",
    "HIGH": "उच्च",
    "CRITICAL": "गंभीर",
    "ELECTRICITY": "बिजली",
    "WATER": "जल",
    "SANITATION": "स्वच्छता",
    "ROADS": "सड़कें",
    "PUBLIC_SERVICES": "लोक सेवाएं",
    "HEALTH": "स्वास्थ्य",
    "EDUCATION": "शिक्षा",
    "OTHER": "अन्य",
    "Language": "भाषा",
    "Theme": "थीम",
    "Light": "लाइट",
    "OFFICER": "अधिकारी",
    "CITIZEN": "नागरिक",
    "ADMIN": "प्रशासक",
    "Logout": "लॉग आउट",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem(STORAGE_KEY) || DEFAULT_LANGUAGE);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ur" ? "rtl" : "ltr";
  }, [language]);

  const value = useMemo(() => {
    const dictionary = {
      ...(translations[language] || {}),
      ...(dashboardTranslations[language] || {}),
    };
    return {
      language,
      setLanguage,
      t: (text) => dictionary[text] || text,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}
